title: Welcome to my GitHub Page!
author: Jacob Roan
email: jacobmroan@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Thanks for looking at my site, and thanks to GitHub for making such excellent tutorials.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
